package org.apache.jsp.dashboard.realstate;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import risk.json.JSONObject;
import risk.json.JSONArray;
import java.util.*;
import java.lang.*;
import java.util.Enumeration;
import java.util.Map;
import risk.util.ParseRequest;
import risk.util.DateUtil;
import java.util.*;
import java.net.URLEncoder;
import risk.util.PageIndex;
import risk.util.StringUtil;
import risk.util.ConfigUtil;
import risk.dashboard.realstate.RealstateMgr;

public final class realstate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

ParseRequest pr = new ParseRequest(request);
DateUtil du = new DateUtil();
String currentDate = du.getCurrentDate("yyyy-MM-dd");
String yesterDay = du.addDay(currentDate, -1);
String preWeekDay = du.addDay(currentDate, -7);
StringUtil su = new StringUtil();
String sDate = pr.getString("sDate", preWeekDay);
String eDate = pr.getString("eDate", currentDate);
String searchKey = pr.getString("searchKey" , "");

RealstateMgr rMgr = new RealstateMgr();

JSONArray arr = rMgr.getRealstateList();


      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Include PAGE TOP -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../inc/inc_page_top.jsp", out, false);
      out.write("\r\n");
      out.write("<!-- // Include PAGE TOP -->\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"realstate.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tgnbIDX = \"0300\";\r\n");
      out.write("\t\tsetPageTitle( \"대구시청 - 실국별 현황분석\" );\r\n");
      out.write("\t\tvar pcode = \"\";\r\n");
      out.write("\r\n");
      out.write("\t\t$(function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//getRealstateList();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tsetTimeout(function(){\r\n");
      out.write("\t\t\t\tpcode = $(\"[name=realstate01]:checked\").val();\r\n");
      out.write("\t\t\t\tgetDvisionList(pcode);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tsetTimeout(function(){\r\n");
      out.write("\t\t\t\t\thndl_search();\t\r\n");
      out.write("\t\t\t\t},100);\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"[name=realstate01]\").change(function(){\t\r\n");
      out.write("\t\t\t\t\t$(\".select_00\").eq(1).text(\"전체\");\r\n");
      out.write("\t\t\t\t\t$(\".select_00\").eq(2).text(\"전체\");\r\n");
      out.write("\t\t\t\t\t$(\".select_00\").eq(3).text(\"전체\");\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tgetDvisionList($(this).val());\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tsetTimeout(function(){\r\n");
      out.write("\t\t\t\t\t\thndl_search();\t\r\n");
      out.write("\t\t\t\t\t},100);\t\t\t\t\t\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#s_sel01\").change(function(){\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tsection02();\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#s_sel02\").change(function(){\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tsection03(1);\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#s_sel03\").change(function(){\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tsection03(1);\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t},100);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#ui_search_input\").keypress(function(e){\r\n");
      out.write("\t\t        if (e.which == 13) {\r\n");
      out.write("\t\t        \thndl_search();\r\n");
      out.write("\t\t        }\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 검색\r\n");
      out.write("\t\tfunction hndl_search(){\r\n");
      out.write("\t\t\tvar sDateChk = $(\"#searchs_dp_start\").val();\r\n");
      out.write("\t\t\tvar eDateChk = $(\"#searchs_dp_end\").val();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(getDateDiff(sDateChk, eDateChk)>365){\r\n");
      out.write("\t\t\t\talert(\"31일까지 검색 가능 합니다.\");\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\t$(\".ui_box_00\").find(\".v0\").fadeIn(80);\r\n");
      out.write("\t\t\t\tscope = $(\"#search_sel_01\").val();\r\n");
      out.write("\t\t\t\tkeyword = $(\"#ui_search_input\").val();\r\n");
      out.write("\t\t\t\tsDate = $(\"#searchs_dp_start\").val();\r\n");
      out.write("\t\t\t\teDate = $(\"#searchs_dp_end\").val();\t\t\r\n");
      out.write("\t\t\t\tpcode = $(\"[name=realstate01]:checked\").val();\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tsection01();\r\n");
      out.write("\t\t\t\tsection02();\r\n");
      out.write("\t\t\t\tsection03(1);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t/* // Spart Chart Default Option\r\n");
      out.write("\t\tvar sparkChartOption = {\r\n");
      out.write("\t\t\t\"type\": \"serial\",\r\n");
      out.write("\t\t\t\"categoryField\": \"category\",\r\n");
      out.write("\t\t\t\"autoMargins\": false,\r\n");
      out.write("\t\t\t\"marginBottom\": 0,\r\n");
      out.write("\t\t\t\"marginLeft\": 0,\r\n");
      out.write("\t\t\t\"marginRight\": 0,\r\n");
      out.write("\t\t\t\"marginTop\": 0,\r\n");
      out.write("\t\t\t\"colors\": [\r\n");
      out.write("\t\t\t\t\"#404142\"\r\n");
      out.write("\t\t\t],\r\n");
      out.write("\t\t\t\"categoryAxis\": {\r\n");
      out.write("\t\t\t\t\"gridPosition\": \"start\",\r\n");
      out.write("\t\t\t\t\"startOnAxis\": true,\r\n");
      out.write("\t\t\t\t\"axisThickness\": 0,\r\n");
      out.write("\t\t\t\t\"axisColor\": \"#FFFFFF\",\r\n");
      out.write("\t\t\t\t\"gridAlpha\": 0,\r\n");
      out.write("\t\t\t\t\"gridThickness\": 0,\r\n");
      out.write("\t\t\t\t\"labelsEnabled\": false,\r\n");
      out.write("\t\t\t\t\"tickLength\": 0\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t\"trendLines\": [],\r\n");
      out.write("\t\t\t\"graphs\": [\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\"balloonText\": \"[[title]] of [[category]]:[[value]]\",\r\n");
      out.write("\t\t\t\t\t\"id\": \"AmGraph-1\",\r\n");
      out.write("\t\t\t\t\t\"title\": \"graph 1\",\r\n");
      out.write("\t\t\t\t\t\"valueField\": \"column-1\"\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t],\r\n");
      out.write("\t\t\t\"guides\": [],\r\n");
      out.write("\t\t\t\"valueAxes\": [\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\"id\": \"ValueAxis-1\",\r\n");
      out.write("\t\t\t\t\t\"axisColor\": \"#FFFFFF\",\r\n");
      out.write("\t\t\t\t\t\"axisThickness\": 0,\r\n");
      out.write("\t\t\t\t\t\"gridAlpha\": 0,\r\n");
      out.write("\t\t\t\t\t\"gridThickness\": 0,\r\n");
      out.write("\t\t\t\t\t\"labelsEnabled\": false,\r\n");
      out.write("\t\t\t\t\t\"tickLength\": -1,\r\n");
      out.write("\t\t\t\t\t\"title\": \"\"\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t],\r\n");
      out.write("\t\t\t\"allLabels\": [],\r\n");
      out.write("\t\t\t\"balloon\": {},\r\n");
      out.write("\t\t\t\"titles\": []\r\n");
      out.write("\t\t}; */\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Include Message Box -->\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../inc/inc_message_box.jsp", out, false);
      out.write("\r\n");
      out.write("\t<!-- // Include Message Box -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- Include HEADER -->\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../inc/inc_header.jsp", out, false);
      out.write("\r\n");
      out.write("\t<!-- // Include HEADER -->\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"page_wrap\" id=\"s_top\">\r\n");
      out.write("\t\t<!-- Content Container -->\r\n");
      out.write("\t\t<div id=\"container\" class=\"\">\r\n");
      out.write("\t\t\t<div id=\"content\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<h2 class=\"invisible\">실국별 현황 분석</h2>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Search -->\r\n");
      out.write("\t\t\t\t<form action=\"#\">\r\n");
      out.write("\t\t\t\t\t<div class=\"f_clear\">\r\n");
      out.write("\t\t\t\t\t\t<section class=\"ui_searchs fr\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3 class=\"invisible\">검색조건</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"ui_search_type\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"dcp\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select id=\"search_sel_01\" class=\"ui_hidden\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1\">제목</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"2\">내용</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"3\" selected>제목 + 내용</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select><label for=\"search_sel_01\" class=\"select_00\"></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" id=\"ui_search_input\" class=\"ui_input_01\" style=\"width:400px\"><label for=\"ui_search_input\" class=\"invisible\">검색어 입력</label>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"ui_search_date\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"ui_datepicker_input_range\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input id=\"searchs_date_range\" type=\"text\" class=\"date_result\" readonly value=\"\"><label for=\"searchs_date_range\" class=\"invisible\">검색기간</label>\t\t<!-- 선택시 input에 'active'클래스 추가 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"calendars\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"arrow\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"calendars_container\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div id=\"searchs_dp_start\" class=\"dp\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div id=\"searchs_dp_end\" class=\"dp\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"btns\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn_ok\"><span>선택완료</span></button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"ui_date_group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"group\"><input id=\"group_01\" type=\"radio\" name=\"date_group\" value=\"7\"><label for=\"group_01\">7월</label></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"group\"><input id=\"group_02\" type=\"radio\" name=\"date_group\" value=\"8\"><label for=\"group_02\">8월</label></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"group\"><input id=\"group_03\" type=\"radio\" name=\"date_group\" value=\"29\"><label for=\"group_03\">30일</label></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"group\"><input id=\"group_04\" type=\"radio\" name=\"date_group\" value=\"6\"><label for=\"group_04\">7일</label></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"group\"><input id=\"group_05\" type=\"radio\" name=\"date_group\" value=\"1\"><label for=\"group_05\">1일</label></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\t\t\t// 날짜 설정\r\n");
      out.write("\t\t\t\t\t\t\t\tvar sel_sDate = getBeforeDay(getToday(), 6);\t\t// 시작 날짜 설정\r\n");
      out.write("\t\t\t\t\t\t\t\tvar sel_eDate = getToday();\t\t\t\t\t\t\t// 종료 날짜 설정\r\n");
      out.write("\t\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"ui_btn_01\" onclick=\"hndl_search()\"><strong>검색</strong></button>\r\n");
      out.write("\t\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<!-- // Search -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- 실국별 현황 분석 -->\r\n");
      out.write("\t\t\t\t<div id=\"s_c3\" class=\"ui_boxs_00\">\r\n");
      out.write("\t\t\t\t\t<div class=\"ui_tab_type01\">\r\n");
      out.write("\t\t\t\t\t\t<ul id=\"realstateList\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t");

						if(arr != null){
							JSONObject obj = null;
							String checked = "";
						for(int i=0 ; i<arr.length() ; i++){
							obj = (JSONObject)arr.get(i);
							checked = "";
							if(i==0){checked = "checked";}
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"realstate01\" class=\"\" value=\"");
      out.print(obj.getString("code") );
      out.write("\" id=\"tab_li_0");
      out.print(i+1);
      out.write('"');
      out.write(' ');
      out.print(checked);
      out.write(">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"bg\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>");
      out.print(obj.getString("name") );
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div><label for=\"tab_li_0");
      out.print(i+1);
      out.write("\"></label></div>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t");
} }
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"realstate01\" class=\"\" id=\"tab_li_02\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"bg\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>교통국</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div><label for=\"tab_li_02\"></label></div>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"realstate01\" class=\"\" id=\"tab_li_03\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"bg\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>기획<br>조정실</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div><label for=\"tab_li_03\"></label></div>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"realstate01\" class=\"\" id=\"tab_li_04\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"bg\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>녹색<br>환경국</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div><label for=\"tab_li_04\"></label></div>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"realstate01\" class=\"\" id=\"tab_li_05\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"bg\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>도시재<br>창조국</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div><label for=\"tab_li_05\"></label></div>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"realstate01\" class=\"\" id=\"tab_li_06\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"bg\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>도시<br>철도건설<br>본부</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div><label for=\"tab_li_06\"></label></div>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"realstate01\" class=\"\" id=\"tab_li_07\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"bg\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>문화<br>체육<br>관광국</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div><label for=\"tab_li_07\"></label></div>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"realstate01\" class=\"\" id=\"tab_li_08\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"bg\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>보건<br>복지국</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div><label for=\"tab_li_08\"></label></div>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"realstate01\" class=\"\" id=\"tab_li_09\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"bg\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>상수도<br>사업<br>본부</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div><label for=\"tab_li_09\"></label></div>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"realstate01\" class=\"\" id=\"tab_li_10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"bg\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>소방<br>안전본부</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div><label for=\"tab_li_10\"></label></div>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"realstate01\" class=\"\" id=\"tab_li_11\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"bg\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>시민<br>안전실</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div><label for=\"tab_li_11\"></label></div>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"realstate01\" class=\"\" id=\"tab_li_12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"bg\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>시민<br>행복<br>교육</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div><label for=\"tab_li_12\"></label></div>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"realstate01\" class=\"\" id=\"tab_li_13\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"bg\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>여성<br>가족<br>청소년국</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div><label for=\"tab_li_13\"></label></div>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"realstate01\" class=\"\" id=\"tab_li_14\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"bg\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>일자리<br>투자국</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div><label for=\"tab_li_14\"></label></div>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"realstate01\" class=\"\" id=\"tab_li_15\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"bg\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>자치<br>행정국</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div><label for=\"tab_li_15\"></label></div>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"realstate01\" class=\"\" id=\"tab_li_16\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"bg\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>통합<br>신공항<br>추진본부</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div><label for=\"tab_li_16\"></label></div>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"realstate01\" class=\"\" id=\"tab_li_17\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"bg\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>혁신<br>성장국</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div><label for=\"tab_li_17\"></label></div>\r\n");
      out.write("\t\t\t\t\t\t\t</li> -->\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<section class=\"ui_box_00 ui_shadow_00 no_bdt\">\r\n");
      out.write("\t\t\t\t\t\t<h3 class=\"no_bd invisible\"><span class=\"ui_bullet_00\">●</span>경제국</h3>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"content p_t_20\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 온라인 동향 -->\r\n");
      out.write("\t\t\t\t\t\t\t<section id=\"s_c3_1\" class=\"ui_box_00\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>온라인 동향</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"title_rc\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"ui_btn_02 ui_shadow_01\" title=\"Excel Download\" onclick=\"excelDownload('1','온라인동향'); return false;\"><span class=\"icon excel\">Excel Download</span></button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"chart_05\" class=\"ui_chart\" style=\"height:250px\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar chartOption = {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"type\": \"serial\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"categoryField\": \"category\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"columnWidth\": 0.7,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"marginTop\": 10,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"colors\": [\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"#4a80c1\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"#726d6e\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"#58b530\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"#116e27\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"#ecb900\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"#a25a25\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"#7258c8\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"#e3458b\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t],\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"addClassNames\": true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"pathToImages\": \"../asset/img/amchart/\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"percentPrecision\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"categoryAxis\": {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"gridPosition\": \"start\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"twoLineMode\": true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"axisColor\": \"#D8D8D8\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"color\": \"#444444\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"gridAlpha\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"tickLength\": 0\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"chartCursor\": {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"enabled\": true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"cursorColor\": \"#000000\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"trendLines\": [],\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"graphs\": [\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"balloonText\": \"<strong>[[title]]</strong> : [[value]]\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"bullet\": \"round\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"bulletBorderThickness\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"bulletSize\": 7,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"id\": \"AmGraph-1\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"lineThickness\": 2,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"title\": \"경제정책관\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"valueField\": \"column-1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"balloonText\": \"<strong>[[title]]</strong> : [[value]]\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"bullet\": \"round\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"bulletBorderThickness\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"bulletSize\": 7,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"id\": \"AmGraph-2\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"lineThickness\": 2,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"title\": \"기계로봇과\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"valueField\": \"column-2\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"balloonText\": \"<strong>[[title]]</strong> : [[value]]\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"bullet\": \"round\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"bulletBorderThickness\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"bulletSize\": 7,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"id\": \"AmGraph-3\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"lineThickness\": 2,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"title\": \"농산유통과\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"valueField\": \"column-3\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"balloonText\": \"<strong>[[title]]</strong> : [[value]]\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"bullet\": \"round\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"bulletBorderThickness\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"bulletSize\": 7,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"id\": \"AmGraph-4\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"lineThickness\": 2,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"title\": \"농수산물도매시장\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"valueField\": \"column-4\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"balloonText\": \"<strong>[[title]]</strong> : [[value]]\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"bullet\": \"round\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"bulletBorderThickness\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"bulletSize\": 7,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"id\": \"AmGraph-5\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"lineThickness\": 2,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"title\": \"대구농업기술센터\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"valueField\": \"column-5\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"balloonText\": \"<strong>[[title]]</strong> : [[value]]\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"bullet\": \"round\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"bulletBorderThickness\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"bulletSize\": 7,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"id\": \"AmGraph-6\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"lineThickness\": 2,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"title\": \"민생경제과\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"valueField\": \"column-6\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"balloonText\": \"<strong>[[title]]</strong> : [[value]]\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"bullet\": \"round\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"bulletBorderThickness\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"bulletSize\": 7,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"id\": \"AmGraph-7\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"lineThickness\": 2,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"title\": \"산단진흥과\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"valueField\": \"column-7\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"balloonText\": \"<strong>[[title]]</strong> : [[value]]\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"bullet\": \"round\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"bulletBorderThickness\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"bulletSize\": 7,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"id\": \"AmGraph-8\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"lineThickness\": 2,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"title\": \"섬유패션과\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"valueField\": \"column-8\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t],\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"guides\": [],\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"valueAxes\": [\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"id\": \"ValueAxis-1\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"axisThickness\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"color\": \"#c0c0c0\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"dashLength\": 2,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"gridAlpha\": 1,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"gridColor\": \"#D8D8D8\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"tickLength\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"title\": \"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t],\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"allLabels\": [],\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"balloon\": {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"color\": \"#FFFFFF\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"fadeOutDuration\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"fillAlpha\": 0.67,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"fillColor\": \"#000000\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"fontSize\": 11,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"horizontalPadding\": 10,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"pointerWidth\": 5,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"shadowAlpha\": 0.3\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"legend\": {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"enabled\": true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"align\": \"center\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"autoMargins\": false,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"color\": \"#444444\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"equalWidths\": false,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"spacing\": 15,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"markerLabelGap\": 6,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"markerSize\": 11,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"markerType\": \"circle\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"valueText\": \"\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"verticalGap\": 0\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"titles\": [],\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"dataProvider\": [\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t/* {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"category\": \"06-01\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-1\": 46,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-2\": 26,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-3\": 16,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-4\": 29,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-5\": 50,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-6\": 10,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-7\": 8,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-8\": 11\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"category\": \"06-01\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-1\": 22,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-2\": 61,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-3\": 16,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-4\": 29,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-5\": 50,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-6\": 10,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-7\": 8,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-8\": 11\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"category\": \"06-01\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-1\": 16,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-2\": 29,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-3\": 16,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-4\": 29,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-5\": 50,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-6\": 10,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-7\": 8,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-8\": 11\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"category\": \"06-01\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-1\": 70,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-2\": 66,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-3\": 16,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-4\": 29,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-5\": 50,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-6\": 10,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-7\": 8,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-8\": 11\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"category\": \"06-01\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-1\": 51,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-2\": 13,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-3\": 16,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-4\": 29,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-5\": 50,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-6\": 10,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-7\": 8,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-8\": 11\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"category\": \"06-01\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-1\": 67,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-2\": 38,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-3\": 16,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-4\": 29,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-5\": 50,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-6\": 10,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-7\": 8,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-8\": 11\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"category\": \"06-01\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-1\": 76,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-2\": 88,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-3\": 16,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-4\": 29,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-5\": 50,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-6\": 10,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-7\": 8,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-8\": 11\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t} */\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t]\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t};\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar chart1 = AmCharts.makeChart(\"chart_05\", chartOption);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tchart1.addListener(\"clickGraphItem\", function($e){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tvar date = $e.item.dataContext.fulldate;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tvar code = \"51@\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tcode += $e.graph.code;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tvar param = \"sDate=\"+date+\"&eDate=\"+date+\"&codeList=\"+code+\"&scope=\"+scope+\"&keyword=\"+keyword;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tpopupOpen( \"../popup/rel_info.jsp\" ,param);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Loader -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"ui_loader v0\"><span class=\"loader\">Load</span></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"ui_loader v1\"><span class=\"loader\"></span><p>saving...</p></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- // Loader -->\r\n");
      out.write("\t\t\t\t\t\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 채널별 성향 -->\r\n");
      out.write("\t\t\t\t\t\t\t<section id=\"s_c3_2\" class=\"ui_box_00 m_t_20\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4 class=\"no_bd\">채널별 성향</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"title_rc\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<strong>부서</strong>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"dcp\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<select id=\"s_sel01\" class=\"ui_hidden\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<!-- <option selected=\"\">전체</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option>경제정책관</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option>기계로봇과</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option>농산유통과</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option>농수산물도매시장</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option>대구농업기술센터</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option>민생경제과</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option>산단진흥과</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option>섬유패션과</option> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</select><label for=\"s_sel01\" class=\"select_00\">전체</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"ui_btn_02 ui_shadow_01\" title=\"Excel Download\" onclick=\"excelDownload('2','채널별 성향'); return false;\"><span class=\"icon excel\">Excel Download</span></button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- 채널 정보량/성향 현황 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"f_clear\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<section class=\"fl\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"content\" style=\"width:300px; height:280px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div id=\"chart_02\" class=\"ui_chart\" style=\"height:280px\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tvar chartOption = {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"type\": \"pie\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"balloonText\": \"<strong>[[category]]</strong><br>[[value]]건\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"innerRadius\": \"50%\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"labelRadius\": -17,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"labelText\": \"[[percents]]%\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"pullOutRadius\": \"0%\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"radius\": \"35%\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"startRadius\": \"0%\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"colors\": [\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t/*\"#3b5999\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"#5bc17a\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"#b13aae\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"#01d6ff\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"#fdd035\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"#d12b10\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"#ed7014\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t*/\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"#5ba1e0\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"#ea7070\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"#888888\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t],\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"marginBottom\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"marginTop\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"pullOutDuration\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"startDuration\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"titleField\": \"category\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"valueField\": \"column-1\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"addClassNames\": true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"color\": \"#FFFFFF\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"percentPrecision\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"allLabels\": [\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"align\": \"center\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"bold\": true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"color\": \"#4761a1\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"id\": \"Label-1\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"size\": 14,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"text\": \"VOLUME\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"y\": 100\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"align\": \"center\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"bold\": true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"color\": \"#444444\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"id\": \"Label-2\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"size\": 30,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"text\": \"0\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"y\": 120\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t],\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"balloon\": {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"color\": \"#FFFFFF\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"fadeOutDuration\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"fillAlpha\": 0.67,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"fillColor\": \"#000000\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"fixedPosition\": false,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"fontSize\": 11,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"horizontalPadding\": 10,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"pointerWidth\": 5,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"shadowAlpha\": 0.3\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"legend\": {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"enabled\": true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"position\": \"bottom\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"align\": \"center\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"autoMargins\": false,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"color\": \"#444444\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"marginLeft\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"marginRight\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"markerLabelGap\": 6,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"markerSize\": 11,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"markerType\": \"circle\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"spacing\": 5,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"verticalGap\" : 2,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"valueText\": \"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"titles\": [],\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"dataProvider\": [\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t/* {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"category\": \"긍정\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-1\": 25\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"category\": \"부정\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-1\": 36\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"category\": \"중립\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-1\": 36\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t} */\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t]\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t};\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tvar chart2 = AmCharts.makeChart(\"chart_02\", chartOption);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tchart2.addListener(\"clickSlice\", function($e){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tvar senti = \"9@\"+$e.dataItem.dataContext.code;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tvar code = $(\"#s_sel01 option:selected\").val().replaceAll(\",\",\"@\");\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tvar codeList = senti+\"/\"+code;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tvar param = \"sDate=\"+sDate+\"&eDate=\"+eDate+\"&codeList=\"+codeList+\"&scope=\"+scope+\"&keyword=\"+keyword;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tpopupOpen( \"../popup/rel_info.jsp\" ,param);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<!-- Loader -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"ui_loader v0\"><span class=\"loader\">Load</span></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"ui_loader v1\"><span class=\"loader\"></span><p>saving...</p></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<!-- // Loader -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- 채널 성향 현황 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<section class=\"fr\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"content\" style=\"width:556px;height:280px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div id=\"chart_03\" class=\"ui_chart\" style=\"height:280px;\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tvar chartOption = {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"type\": \"serial\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"categoryField\": \"category\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"columnWidth\": 0.4,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"marginBottom\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"marginTop\": 20,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"colors\": [\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"#5ba1e0\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"#ea7070\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"#888888\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t],\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"addClassNames\": true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"pathToImages\": \"../asset/img/amchart/\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"percentPrecision\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"categoryAxis\": {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"autoRotateAngle\": 45,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"autoRotateCount\": 12,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"autoWrap\": true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"gridPosition\": \"start\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"twoLineMode\": true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"axisColor\": \"#D8D8D8\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"color\": \"#444444\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"gridAlpha\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"tickLength\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"minHorizontalGap\": 0\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"chartCursor\": {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"enabled\": true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"cursorColor\": \"#000000\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"trendLines\": [],\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"graphs\": [\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"balloonText\": \"<strong>[[title]]</strong> : [[value]]\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"bulletBorderThickness\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"bulletSize\": 5,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"fillAlphas\": 1,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"id\": \"AmGraph-1\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"markerType\": \"circle\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"title\": \"긍정\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"code\": \"1\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"type\": \"column\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"valueField\": \"column-1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"balloonText\": \"<strong>[[title]]</strong> : [[value]]\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"bulletBorderThickness\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"bulletSize\": 5,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"fillAlphas\": 1,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"id\": \"AmGraph-2\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"markerType\": \"circle\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"title\": \"부정\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"code\": \"2\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"type\": \"column\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"valueField\": \"column-2\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"balloonText\": \"<strong>[[title]]</strong> : [[value]]\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"bulletBorderThickness\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"bulletSize\": 5,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"fillAlphas\": 1,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"id\": \"AmGraph-3\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"markerType\": \"circle\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"title\": \"중립\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"code\": \"3\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"type\": \"column\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"valueField\": \"column-3\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t],\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"guides\": [],\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"valueAxes\": [\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"id\": \"ValueAxis-1\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"stackType\": \"regular\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"axisThickness\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"color\": \"#c0c0c0\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"dashLength\": 2,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"gridAlpha\": 1,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"gridColor\": \"#D8D8D8\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"tickLength\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"title\": \"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"id\": \"ValueAxis-2\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"maximum\": 100,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"position\": \"right\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"stackType\": \"regular\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"unit\": \"%\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"autoGridCount\": false,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"axisThickness\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"color\": \"#c0c0c0\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"dashLength\": 2,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"gridAlpha\": 1,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"gridColor\": \"#D8D8D8\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"gridCount\": 2,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"gridThickness\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"tickLength\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"title\": \"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t],\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"allLabels\": [],\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"balloon\": {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"color\": \"#FFFFFF\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"fadeOutDuration\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"fillAlpha\": 0.67,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"fillColor\": \"#000000\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"fontSize\": 11,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"horizontalPadding\": 10,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"pointerWidth\": 5,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"shadowAlpha\": 0.3\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"legend\": {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"enabled\": true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"align\": \"center\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"autoMargins\": false,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"color\": \"#444444\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"equalWidths\": false,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"marginLeft\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"marginRight\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"markerLabelGap\": 6,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"markerSize\": 11,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"markerType\": \"circle\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"spacing\": 15,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"useGraphSettings\": true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"valueText\": \"\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"verticalGap\": 2\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"titles\": [],\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"dataProvider\": [\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t/* {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"category\": \"언론\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-1\": 46,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-2\": 46,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-3\": 91\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"category\": \"포탈\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-1\": 22,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-2\": 61,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-3\": 48\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"category\": \"블로그\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-1\": 16,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-2\": 29,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-3\": 68\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"category\": \"카페\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-1\": 70,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-2\": 66,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-3\": 5\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"category\": \"커뮤니티\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-1\": 51,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-2\": 13,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-3\": 88\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"category\": \"트위터\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-1\": 67,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-2\": 38,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-3\": 4\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"category\": \"페이스북\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-1\": 76,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-2\": 88,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-3\": 62\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"category\": \"대구광역시\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-1\": 76,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-2\": 88,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column-3\": 62\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t} */\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t]\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t};\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tvar chart3 = AmCharts.makeChart(\"chart_03\", chartOption);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tchart3.addListener(\"clickGraphItem\", function($e){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tvar type6 = \"6@\"+$e.item.dataContext.code;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tvar senti = \"9@\"+$e.graph.code;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tvar code = $(\"#s_sel01 option:selected\").val().replaceAll(\",\",\"@\");\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tvar codeList = type6+\"/\"+senti+\"/\"+code;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tvar param = \"sDate=\"+sDate+\"&eDate=\"+eDate+\"&codeList=\"+codeList+\"&scope=\"+scope+\"&keyword=\"+keyword;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tpopupOpen( \"../popup/rel_info.jsp\" ,param);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<!-- Loader -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"ui_loader v0\"><span class=\"loader\">Load</span></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"ui_loader v1\"><span class=\"loader\"></span><p>saving...</p></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<!-- // Loader -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- // 채널 성향 현황 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- // 채널 정보량/성향 현황 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Loader -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"ui_loader v0\"><span class=\"loader\">Load</span></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"ui_loader v1\"><span class=\"loader\"></span><p>saving...</p></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- // Loader -->\r\n");
      out.write("\t\t\t\t\t\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 관련정보 -->\r\n");
      out.write("\t\t\t\t\t\t\t<section id=\"s_c3_3\" class=\"ui_box_00 m_t_20\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4 class=\"no_bd\">관련정보</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"title_rc\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<strong>성향</strong>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"dcp\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<select id=\"s_sel02\" class=\"ui_hidden\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"\" selected>전체</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"1\" >긍정</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"2\" >부정</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"3\" >중립</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</select><label for=\"s_sel02\" class=\"select_00\"></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<strong>부서</strong>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"dcp\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<select id=\"s_sel03\" class=\"ui_hidden\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option selected>전체</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</select><label for=\"s_sel03\" class=\"select_00\"></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"ui_btn_02 ui_shadow_01\" title=\"Excel Download\" onclick=\"excelDownload('3','관련정보'); return false;\"><span class=\"icon excel\">Excel Download</span></button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!--관련정보 목록 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"ui_boxs_00\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<section id=\"s_c8_1\" class=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"ui_board_list_00\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<caption>관련정보 목록</caption>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<col style=\"width:120px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<col>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<col style=\"width:100px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<col style=\"width:70px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<col style=\"width:150px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<th scope=\"col\"><span>날짜</span></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<th scope=\"col\"><span>제목</span></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<th scope=\"col\"><span>출처</span></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<th scope=\"col\"><span>성향</span></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<th scope=\"col\"><span>부서</span></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<tbody id=\"section03_list\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<tr><td colspan=\"5\" style=\"height:300px\">데이터가 없습니다</td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<!-- <tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>2017-01-01</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td class=\"title\"><a href=\"#\" target=\"_blank\" title=\"\">섬유산업 미래 융복합 혁신기술의 방향 제시와 새로운 비즈니스 플랫폼</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td><span title=\"네이버\">네이버블로그</span></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td><span>중립</span></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td><span title=\"경제정책관\">경제정책관</span></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>2017-01-01</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td class=\"title\"><a href=\"#\" target=\"_blank\" title=\"\">섬유산업 미래 융복합 혁신기술의 방향 제시와 새로운 비즈니스 플랫폼</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td><span title=\"네이버\">네이버블로그</span></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td><span>중립</span></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td><span title=\"대구농업기술센터\">대구농업기술센터</span></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<tr><td colspan=\"5\"></td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<tr><td colspan=\"5\"></td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<tr><td colspan=\"5\"></td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<tr><td colspan=\"5\"></td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<tr><td colspan=\"5\"></td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<tr><td colspan=\"5\"></td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<tr><td colspan=\"5\"></td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<tr><td colspan=\"5\"></td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<tr><td colspan=\"5\"></td></tr> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"paginate\" id=\"section03_Paging\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<!-- <a href=\"#\" class=\"page_first disabled\">처음 페이지</a>\t\t버튼 활성화시 disabled 클래스 제거\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"page_prev disabled\">이전페이지</a>\t\t버튼 활성화시 disabled 클래스 제거\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"active\" onclick=\"popupOpen( '../popup/rel_info.jsp' );return false;\">1</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\" onclick=\"popupOpen( '../popup/rel_info.jsp' );return false;\">2</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\">3</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\">4</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\">5</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\">6</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\">7</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\">8</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\">9</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\">10</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"page_next\">다음페이지</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"page_last\">마지막 페이지</a> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<!-- Loader -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"ui_loader v0\"><span class=\"loader\">Load</span></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"ui_loader v1\"><span class=\"loader\"></span><p>saving...</p></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<!-- // Loader -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- // 관련정보 목록 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Loader -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"ui_loader v0\"><span class=\"loader\">Load</span></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"ui_loader v1\"><span class=\"loader\"></span><p>saving...</p></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- // Loader -->\r\n");
      out.write("\t\t\t\t\t\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\t\t\t// http://mistic100.github.io/jQCloud/ - 태그 클라우드 사용법 : 좌측 URL 참조\r\n");
      out.write("\t\t\t\t\t\t\t\t$( \"#tag_cloud_01\" ).each( function(){\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar words =[\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{text: \"ITEM 01\", weight: 25, link : \"javascript:popupOpen( '../popup/rel_info.jsp', 'a=1' )\" },\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{text: \"ITEM 02\", weight: 24, link : \"javascript:popupOpen( '../popup/rel_info.jsp', 'a=1' )\" },\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{text: \"ITEM 03\", weight: 23, link : \"javascript:popupOpen( '../popup/rel_info.jsp', 'a=1' )\" },\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{text: \"ITEM 04\", weight: 22, link : \"javascript:popupOpen( '../popup/rel_info.jsp', 'a=1' )\" },\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{text: \"ITEM 05\", weight: 21, link : \"javascript:popupOpen( '../popup/rel_info.jsp', 'a=1' )\" },\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{text: \"ITEM 06\", weight: 20, link : \"javascript:popupOpen( '../popup/rel_info.jsp', 'a=1' )\" },\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{text: \"ITEM 07\", weight: 19, link : \"javascript:popupOpen( '../popup/rel_info.jsp', 'a=1' )\" },\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{text: \"ITEM 08\", weight: 18, link : \"javascript:popupOpen( '../popup/rel_info.jsp', 'a=1' )\" },\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{text: \"ITEM 09\", weight: 17, link : \"javascript:popupOpen( '../popup/rel_info.jsp', 'a=1' )\" },\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{text: \"ITEM 10\", weight: 16, link : \"javascript:popupOpen( '../popup/rel_info.jsp', 'a=1' )\" },\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{text: \"ITEM 11\", weight: 15, link : \"javascript:popupOpen( '../popup/rel_info.jsp', 'a=1' )\" },\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{text: \"ITEM 12\", weight: 14, link : \"javascript:popupOpen( '../popup/rel_info.jsp', 'a=1' )\" },\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{text: \"ITEM 13\", weight: 13, link : \"javascript:popupOpen( '../popup/rel_info.jsp', 'a=1' )\" },\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{text: \"ITEM 14\", weight: 12, link : \"javascript:popupOpen( '../popup/rel_info.jsp', 'a=1' )\" },\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{text: \"ITEM 15\", weight: 11, link : \"javascript:popupOpen( '../popup/rel_info.jsp', 'a=1' )\" },\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{text: \"ITEM 16\", weight: 10, link : \"javascript:popupOpen( '../popup/rel_info.jsp', 'a=1' )\" },\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{text: \"ITEM 17\", weight: 9, link : \"javascript:popupOpen( '../popup/rel_info.jsp', 'a=1' )\" },\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{text: \"ITEM 18\", weight: 8, link : \"javascript:popupOpen( '../popup/rel_info.jsp', 'a=1' )\" },\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{text: \"ITEM 19\", weight: 7, link : \"javascript:popupOpen( '../popup/rel_info.jsp', 'a=1' )\" },\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{text: \"ITEM 20\", weight: 6, link : \"javascript:popupOpen( '../popup/rel_info.jsp', 'a=1' )\" }\r\n");
      out.write("\t\t\t\t\t\t\t\t\t];\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$( this ).jQCloud( words, {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tautoResize: true\r\n");
      out.write("\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t$( \"#tag_cloud_02\" ).each( function(){\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar words =[\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{text: \"ITEM 01\", weight: 25, link : \"javascript:popupOpen( '../popup/rel_info.jsp', 'a=1' )\" },\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{text: \"ITEM 02\", weight: 24, link : \"javascript:popupOpen( '../popup/rel_info.jsp', 'a=1' )\" },\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{text: \"ITEM 03\", weight: 23, link : \"javascript:popupOpen( '../popup/rel_info.jsp', 'a=1' )\" },\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{text: \"ITEM 04\", weight: 22, link : \"javascript:popupOpen( '../popup/rel_info.jsp', 'a=1' )\" },\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{text: \"ITEM 05\", weight: 21, link : \"javascript:popupOpen( '../popup/rel_info.jsp', 'a=1' )\" },\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{text: \"ITEM 06\", weight: 20, link : \"javascript:popupOpen( '../popup/rel_info.jsp', 'a=1' )\" },\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{text: \"ITEM 07\", weight: 19, link : \"javascript:popupOpen( '../popup/rel_info.jsp', 'a=1' )\" },\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{text: \"ITEM 08\", weight: 18, link : \"javascript:popupOpen( '../popup/rel_info.jsp', 'a=1' )\" },\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{text: \"ITEM 09\", weight: 17, link : \"javascript:popupOpen( '../popup/rel_info.jsp', 'a=1' )\" },\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{text: \"ITEM 10\", weight: 16, link : \"javascript:popupOpen( '../popup/rel_info.jsp', 'a=1' )\" },\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{text: \"ITEM 11\", weight: 15, link : \"javascript:popupOpen( '../popup/rel_info.jsp', 'a=1' )\" },\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{text: \"ITEM 12\", weight: 14, link : \"javascript:popupOpen( '../popup/rel_info.jsp', 'a=1' )\" },\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{text: \"ITEM 13\", weight: 13, link : \"javascript:popupOpen( '../popup/rel_info.jsp', 'a=1' )\" },\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{text: \"ITEM 14\", weight: 12, link : \"javascript:popupOpen( '../popup/rel_info.jsp', 'a=1' )\" },\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{text: \"ITEM 15\", weight: 11, link : \"javascript:popupOpen( '../popup/rel_info.jsp', 'a=1' )\" },\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{text: \"ITEM 16\", weight: 10, link : \"javascript:popupOpen( '../popup/rel_info.jsp', 'a=1' )\" },\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{text: \"ITEM 17\", weight: 9, link : \"javascript:popupOpen( '../popup/rel_info.jsp', 'a=1' )\" },\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{text: \"ITEM 18\", weight: 8, link : \"javascript:popupOpen( '../popup/rel_info.jsp', 'a=1' )\" },\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{text: \"ITEM 19\", weight: 7, link : \"javascript:popupOpen( '../popup/rel_info.jsp', 'a=1' )\" },\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{text: \"ITEM 20\", weight: 6, link : \"javascript:popupOpen( '../popup/rel_info.jsp', 'a=1' )\" }\r\n");
      out.write("\t\t\t\t\t\t\t\t\t];\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$( this ).jQCloud( words, {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tautoResize: true\r\n");
      out.write("\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t$( \"#tag_cloud_03\" ).each( function(){\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar words =[\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{text: \"ITEM 01\", weight: 25, link : \"javascript:popupOpen( '../popup/rel_info.jsp', 'a=1' )\" },\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{text: \"ITEM 02\", weight: 24, link : \"javascript:popupOpen( '../popup/rel_info.jsp', 'a=1' )\" },\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{text: \"ITEM 03\", weight: 23, link : \"javascript:popupOpen( '../popup/rel_info.jsp', 'a=1' )\" },\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{text: \"ITEM 04\", weight: 22, link : \"javascript:popupOpen( '../popup/rel_info.jsp', 'a=1' )\" },\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{text: \"ITEM 05\", weight: 21, link : \"javascript:popupOpen( '../popup/rel_info.jsp', 'a=1' )\" },\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{text: \"ITEM 06\", weight: 20, link : \"javascript:popupOpen( '../popup/rel_info.jsp', 'a=1' )\" },\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{text: \"ITEM 07\", weight: 19, link : \"javascript:popupOpen( '../popup/rel_info.jsp', 'a=1' )\" },\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{text: \"ITEM 08\", weight: 18, link : \"javascript:popupOpen( '../popup/rel_info.jsp', 'a=1' )\" },\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{text: \"ITEM 09\", weight: 17, link : \"javascript:popupOpen( '../popup/rel_info.jsp', 'a=1' )\" },\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{text: \"ITEM 10\", weight: 16, link : \"javascript:popupOpen( '../popup/rel_info.jsp', 'a=1' )\" },\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{text: \"ITEM 11\", weight: 15, link : \"javascript:popupOpen( '../popup/rel_info.jsp', 'a=1' )\" },\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{text: \"ITEM 12\", weight: 14, link : \"javascript:popupOpen( '../popup/rel_info.jsp', 'a=1' )\" },\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{text: \"ITEM 13\", weight: 13, link : \"javascript:popupOpen( '../popup/rel_info.jsp', 'a=1' )\" },\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{text: \"ITEM 14\", weight: 12, link : \"javascript:popupOpen( '../popup/rel_info.jsp', 'a=1' )\" },\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{text: \"ITEM 15\", weight: 11, link : \"javascript:popupOpen( '../popup/rel_info.jsp', 'a=1' )\" },\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{text: \"ITEM 16\", weight: 10, link : \"javascript:popupOpen( '../popup/rel_info.jsp', 'a=1' )\" },\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{text: \"ITEM 17\", weight: 9, link : \"javascript:popupOpen( '../popup/rel_info.jsp', 'a=1' )\" },\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{text: \"ITEM 18\", weight: 8, link : \"javascript:popupOpen( '../popup/rel_info.jsp', 'a=1' )\" },\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{text: \"ITEM 19\", weight: 7, link : \"javascript:popupOpen( '../popup/rel_info.jsp', 'a=1' )\" },\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t{text: \"ITEM 20\", weight: 6, link : \"javascript:popupOpen( '../popup/rel_info.jsp', 'a=1' )\" }\r\n");
      out.write("\t\t\t\t\t\t\t\t\t];\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$( this ).jQCloud( words, {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tautoResize: true\r\n");
      out.write("\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t</script> -->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- Loader -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"ui_loader v0\"><span class=\"loader\">Load</span></div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"ui_loader v1\"><span class=\"loader\"></span><p>saving...</p></div>\r\n");
      out.write("\t\t\t\t\t\t<!-- // Loader -->\r\n");
      out.write("\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- // 실국별 현황 분석 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Include Footer -->\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../inc/inc_footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t<!-- // Include Footer -->\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else log(t.getMessage(), t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
