package org.apache.jsp.dashboard.summary;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import risk.util.ConfigUtil;
import java.util.*;
import java.lang.*;
import java.util.Enumeration;
import java.util.Map;
import risk.util.ParseRequest;
import risk.util.DateUtil;
import java.util.*;
import java.net.URLEncoder;
import risk.util.PageIndex;
import risk.util.StringUtil;
import risk.util.ConfigUtil;

public final class summary_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList(1);
    _jspx_dependants.add("/dashboard/summary/../../riskv3/inc/sessioncheck.jsp");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
//@ page contentType="text/html; charset=euc-kr"
      out.write("\r\n");
      out.write("\r\n");

    
	String SS_M_NO = (String)session.getAttribute("SS_M_NO")   == null ? "": (String)session.getAttribute("SS_M_NO")  ;
    String SS_M_ID = (String)session.getAttribute("SS_M_ID")   == null ? "": (String)session.getAttribute("SS_M_ID")  ;
    String SS_M_NAME = (String)session.getAttribute("SS_M_NAME") == null ? "": (String)session.getAttribute("SS_M_NAME");
    String SS_MG_NO = (String)session.getAttribute("SS_MG_NO")  == null ? "": (String)session.getAttribute("SS_MG_NO") ;
	String SS_TITLE = (String)session.getAttribute("SS_TITLE")  == null ? "": (String)session.getAttribute("SS_TITLE");
    String SS_URL =   (String)session.getAttribute("SS_URL")    == null ? "": (String)session.getAttribute("SS_URL") ;
    String SS_M_DEPT =   (String)session.getAttribute("SS_M_DEPT")    == null ? "": (String)session.getAttribute("SS_M_DEPT") ;    
    String SS_M_IP =   (String)session.getAttribute("SS_M_IP")    == null ? "": (String)session.getAttribute("SS_M_IP") ;    
    String SS_M_MAIL =   (String)session.getAttribute("SS_M_MAIL")    == null ? "": (String)session.getAttribute("SS_M_MAIL") ;    
    
	String SS_ML_URL = javax.servlet.http.HttpUtils.getRequestURL(request).toString();
	
	String SS_SEARCHDATE = (String)session.getAttribute("SS_SEARCHDATE")    == null ? "": (String)session.getAttribute("SS_SEARCHDATE") ;
	
	
    

	if ((SS_M_ID.equals("")) || !SS_M_IP.equals(request.getRemoteAddr()) ) {
		ConfigUtil cu = new ConfigUtil();
		out.print("<SCRIPT Language=JavaScript>");
		//out.print("window.setTimeout( \" top.document.location = "+cu.getConfig("URL")+"'riskv3/error/sessionerror.jsp' \") ");
		out.print("top.document.location = '"+cu.getConfig("URL")+"riskv3/error/sessionerror.jsp'");
        out.print("</SCRIPT>");
    }
	

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

ParseRequest pr = new ParseRequest(request);
DateUtil du = new DateUtil();
String currentDate = du.getCurrentDate("yyyy-MM-dd");
String yesterDay = du.addDay(currentDate, -1);
String preWeekDay = du.addDay(currentDate, -7);
StringUtil su = new StringUtil();
String sDate = pr.getString("sDate", preWeekDay);
String eDate = pr.getString("eDate", currentDate);
String searchKey = pr.getString("searchKey" , "");


      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Include PAGE TOP -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../inc/inc_page_top.jsp", out, false);
      out.write("\r\n");
      out.write("<!-- // Include PAGE TOP -->\r\n");
      out.write("<body>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"summary.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tgnbIDX = \"0100\";\r\n");
      out.write("\t\tsetPageTitle( \"대구광역시 - Summary\" );\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(function(){\r\n");
      out.write("\t\t\t// Date picker 설정\r\n");
      out.write("\t\t\t// 달력 START\r\n");
      out.write("\t\t\tif( $( \".ui_datepicker_input\" ).length > 0 ) {\r\n");
      out.write("\t\t\t\t$( \".ui_datepicker_input\" ).datepicker({\r\n");
      out.write("\t\t\t\t\tdateFormat: \"yy-mm-dd\",\r\n");
      out.write("\t\t\t\t\tmonthNames: [ \"1월\", \"2월\", \"3월\", \"4월\", \"5월\", \"6월\", \"7월\", \"8월\", \"9월\", \"10월\", \"11월\", \"12월\" ],\r\n");
      out.write("\t\t\t\t\tdayNamesMin: ['일','월','화','수','목','금','토']\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t$( \".input_date_first.ui_datepicker_input\" ).datepicker().change(function(){\r\n");
      out.write("\t\t\t\t\tvar tempDate = $( this ).datepicker(\"getDate\");\r\n");
      out.write("\t\t\t\t\tvar tempDate2 = $( this ).datepicker(\"getDate\");\r\n");
      out.write("\t\t\t\t\ttempDate2.setDate( tempDate2.getDate() + 30 );\r\n");
      out.write("\t\t\t\t\t$( this ).parent().find( \".date_month\" ).html( ( tempDate.getMonth() + 1 ) + \"월\" );\r\n");
      out.write("\t\t\t\t\t$( this ).parent().find( \".date_date\" ).html( \"\" + tempDate.getDate() );\r\n");
      out.write("\t\t\t\t\t$( this ).parent().parent().find( \".input_date_last.ui_datepicker_input\" ).datepicker(\"option\", \"minDate\", $( this ).val());\r\n");
      out.write("\t\t\t\t\t$( this ).parent().parent().find( \".input_date_last.ui_datepicker_input\" ).datepicker(\"option\", \"maxDate\", tempDate2);\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t$( \".input_date_last.ui_datepicker_input\" ).datepicker().change(function(){\r\n");
      out.write("\t\t\t\t\tvar tempDate = $( this ).datepicker(\"getDate\");\r\n");
      out.write("\t\t\t\t\t$( this ).parent().find( \".date_month\" ).html( ( tempDate.getMonth() + 1 ) + \"월\" );\r\n");
      out.write("\t\t\t\t\t$( this ).parent().find( \".date_date\" ).html( \"\" + tempDate.getDate() );\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t// 달력 END\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t// 검색\r\n");
      out.write("\t\tfunction hndl_search(){\r\n");
      out.write("\t\t\tvar sDateChk = $(\"#searchs_dp_start\").val();\r\n");
      out.write("\t\t\tvar eDateChk = $(\"#searchs_dp_end\").val();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(getDateDiff(sDateChk, eDateChk)>365){\r\n");
      out.write("\t\t\t\talert(\"31일까지 검색 가능 합니다.\");\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\t$(\".ui_box_00\").find(\".v0\").fadeIn(80);\r\n");
      out.write("\t\t\t\tscope = $(\"#search_sel_01\").val();\r\n");
      out.write("\t\t\t\tkeyword = $(\"#ui_search_input\").val();\r\n");
      out.write("\t\t\t\tsDate = $(\"#searchs_dp_start\").val();\r\n");
      out.write("\t\t\t\teDate = $(\"#searchs_dp_end\").val();\r\n");
      out.write("\t\t\t\ttier = \"\";\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$('[name=\"tier\"]').each(function() {\r\n");
      out.write("\t\t\t\t\tif($(this).is(\":checked\")==true){\r\n");
      out.write("\t\t\t\t\t\tif(tier == \"\"){\r\n");
      out.write("\t\t\t\t\t\t\ttier = $(this).val();\r\n");
      out.write("\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\ttier += \",\"+$(this).val();\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t \t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tsection01();\t//온라인 동향\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tsetTimeout(function(){\r\n");
      out.write("\t\t\t\t\tsection02();    //주요시정 채널 별 성향\t\r\n");
      out.write("\t\t\t\t},400);\r\n");
      out.write("\t\t\t\tsetTimeout(function(){\r\n");
      out.write("\t\t\t\t\tsection04(1);    //포탈 TOP 노출 현황\t\r\n");
      out.write("\t\t\t\t},600);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#portal_tbody tr:first-child\").addClass(\"active\");\r\n");
      out.write("\t\t\t\tsummary.portalSearch(1);\t//포탈댓글 형황\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tsection06(\"1\");\t// 알리미앱글 목록\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).ready(function(){\r\n");
      out.write("\t\t\thndl_search();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#ui_search_input\").keypress(function(e){\r\n");
      out.write("\t\t        if (e.which == 13) {\r\n");
      out.write("\t\t        \thndl_search();\r\n");
      out.write("\t\t        }\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"[name=s_c6_1_radio]\").click(function(){\r\n");
      out.write("\t\t\t\t$(\".ui_box_00\").eq(3).find(\".v0\").fadeIn(80);\r\n");
      out.write("\t\t\t\tsection04(1);\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"[name=s_c6_2_radio]\").click(function(){\r\n");
      out.write("\t\t\t\tsummary.portalSearch(1);\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t// Spart Chart Default Option\r\n");
      out.write("\t\tvar sparkChartOption = {\r\n");
      out.write("\t\t\t\"type\": \"serial\",\r\n");
      out.write("\t\t\t\"categoryField\": \"category\",\r\n");
      out.write("\t\t\t\"autoMargins\": false,\r\n");
      out.write("\t\t\t\"marginBottom\": 0,\r\n");
      out.write("\t\t\t\"marginLeft\": 0,\r\n");
      out.write("\t\t\t\"marginRight\": 0,\r\n");
      out.write("\t\t\t\"marginTop\": 0,\r\n");
      out.write("\t\t\t\"colors\": [\r\n");
      out.write("\t\t\t\t\"#404142\"\r\n");
      out.write("\t\t\t],\r\n");
      out.write("\t\t\t\"categoryAxis\": {\r\n");
      out.write("\t\t\t\t\"gridPosition\": \"start\",\r\n");
      out.write("\t\t\t\t\"startOnAxis\": true,\r\n");
      out.write("\t\t\t\t\"axisThickness\": 0,\r\n");
      out.write("\t\t\t\t\"axisColor\": \"#FFFFFF\",\r\n");
      out.write("\t\t\t\t\"gridAlpha\": 0,\r\n");
      out.write("\t\t\t\t\"gridThickness\": 0,\r\n");
      out.write("\t\t\t\t\"labelsEnabled\": false,\r\n");
      out.write("\t\t\t\t\"tickLength\": 0\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t\"trendLines\": [],\r\n");
      out.write("\t\t\t\"graphs\": [\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\"balloonText\": \"[[title]] of [[category]]:[[value]]\",\r\n");
      out.write("\t\t\t\t\t\"id\": \"AmGraph-1\",\r\n");
      out.write("\t\t\t\t\t\"title\": \"graph 1\",\r\n");
      out.write("\t\t\t\t\t\"valueField\": \"column-1\"\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t],\r\n");
      out.write("\t\t\t\"guides\": [],\r\n");
      out.write("\t\t\t\"valueAxes\": [\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\"id\": \"ValueAxis-1\",\r\n");
      out.write("\t\t\t\t\t\"axisColor\": \"#FFFFFF\",\r\n");
      out.write("\t\t\t\t\t\"axisThickness\": 0,\r\n");
      out.write("\t\t\t\t\t\"gridAlpha\": 0,\r\n");
      out.write("\t\t\t\t\t\"gridThickness\": 0,\r\n");
      out.write("\t\t\t\t\t\"labelsEnabled\": false,\r\n");
      out.write("\t\t\t\t\t\"tickLength\": -1,\r\n");
      out.write("\t\t\t\t\t\"title\": \"\"\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t],\r\n");
      out.write("\t\t\t\"allLabels\": [],\r\n");
      out.write("\t\t\t\"balloon\": {},\r\n");
      out.write("\t\t\t\"titles\": []\r\n");
      out.write("\t\t};\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Include Message Box -->\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../inc/inc_message_box.jsp", out, false);
      out.write("\r\n");
      out.write("\t<!-- // Include Message Box -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- Include HEADER -->\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../inc/inc_header.jsp", out, false);
      out.write("\r\n");
      out.write("\t<!-- // Include HEADER -->\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"page_wrap\" id=\"s_top\">\r\n");
      out.write("\t\t<!-- Content Container -->\r\n");
      out.write("\t\t<div id=\"container\" class=\"p_summary\">\r\n");
      out.write("\t\t\t<div id=\"content\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<h2 class=\"invisible\">여론동향</h2>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Search -->\r\n");
      out.write("\t\t\t\t<form action=\"#\" class=\"section_hidden\" >\r\n");
      out.write("\t\t\t\t\t<div class=\"f_clear\" >\r\n");
      out.write("\t\t\t\t\t\t<section class=\"ui_searchs fr\" >\r\n");
      out.write("\t\t\t\t\t\t\t<h3 class=\"invisible\">검색조건</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"ui_search_type\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"dcp\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select id=\"search_sel_01\" class=\"ui_hidden\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1\">제목</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"2\">내용</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"3\" selected>제목 + 내용</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select><label for=\"search_sel_01\" class=\"select_00\"></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" id=\"ui_search_input\" class=\"ui_input_01\" style=\"width:205px\"><label for=\"ui_search_input\" class=\"invisible\">검색어 입력</label>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"ui_search_date\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"ui_datepicker_input_range\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input id=\"searchs_date_range\" type=\"text\" class=\"date_result\" readonly value=\"\"><label for=\"searchs_date_range\" class=\"invisible\">검색기간</label>\t\t<!-- 선택시 input에 'active'클래스 추가 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"calendars\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"arrow\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"calendars_container\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div id=\"searchs_dp_start\" class=\"dp\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div id=\"searchs_dp_end\" class=\"dp\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"btns\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn_ok\"><span>선택완료</span></button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"ui_date_group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"group\"><input id=\"group_01\" type=\"radio\" name=\"date_group\" value=\"7\"><label for=\"group_01\">7월</label></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"group\"><input id=\"group_02\" type=\"radio\" name=\"date_group\" value=\"8\"><label for=\"group_02\">8월</label></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"group\"><input id=\"group_03\" type=\"radio\" name=\"date_group\" value=\"29\"><label for=\"group_03\">30일</label></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"group\"><input id=\"group_04\" type=\"radio\" name=\"date_group\" value=\"6\"><label for=\"group_04\">7일</label></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"group\"><input id=\"group_05\" type=\"radio\" name=\"date_group\" value=\"1\"><label for=\"group_05\">1일</label></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"ui_icon_box line\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"ui_icon_group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"group\"><input type=\"checkbox\" name=\"tier\" value=\"1\" id=\"tier01\"><label for=\"tier01\">Tier1</label></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"group\"><input type=\"checkbox\" name=\"tier\" value=\"2\" id=\"tier02\"><label for=\"tier02\">Tier2</label></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"group\"><input type=\"checkbox\" name=\"tier\" value=\"3\" id=\"tier03\"><label for=\"tier03\">Tier3</label></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"group\"><input type=\"checkbox\" name=\"tier\" value=\"4\" id=\"tier04\"><label for=\"tier04\">Tier4</label></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"group\"><input type=\"checkbox\" name=\"tier\" value=\"5\" id=\"tier05\"><label for=\"tier05\">Tier5</label></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t <script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\t\t\t// 날짜 설정\r\n");
      out.write("\t\t\t\t\t\t\t\tvar sel_sDate = getBeforeDay(getToday(), 6);\t\t// 시작 날짜 설정\r\n");
      out.write("\t\t\t\t\t\t\t\tvar sel_eDate = getToday();\t\t\t\t\t\t\t// 종료 날짜 설정\r\n");
      out.write("\t\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"ui_btn_01\" onclick=\"hndl_search()\"><strong>검색</strong></button>\r\n");
      out.write("\t\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<!-- // Search -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- 온라인 동향 -->\r\n");
      out.write("\t\t\t\t<div class=\"ui_boxs_00\">\r\n");
      out.write("\t\t\t\t\t<section id=\"s_c4_1\" class=\"ui_box_00 ui_shadow_00\">\r\n");
      out.write("\t\t\t\t\t\t<h3><span class=\"ui_bullet_00\">●</span>온라인 동향</h3>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"title_rc\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"ui_btn_02 ui_shadow_01\" title=\"Excel Download\" onclick=\"excelDownload('1', '온라인 동향'); return false;\"><span class=\"icon excel\">Excel Download</span></button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"chart_c4_01\" class=\"ui_chart\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar chart1;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t(function(){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvar chartOption = {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"type\": \"serial\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"categoryField\": \"category\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"columnWidth\": 0.4,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"marginBottom\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"marginTop\": 10,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"colors\": [\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"#0083cc\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"#db9e4e\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t],\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"addClassNames\": true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"pathToImages\": \"../asset/img/amchart/\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"percentPrecision\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"categoryAxis\": {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"gridPosition\": \"start\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"twoLineMode\": true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"axisColor\": \"#D8D8D8\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"color\": \"#444444\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"gridAlpha\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"tickLength\": 0\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"chartCursor\": {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"enabled\": true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"cursorColor\": \"#000000\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"chartScrollbar\": {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"enabled\": true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"dragIconHeight\": 25,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"dragIconWidth\": 25,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"offset\": 20,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"scrollbarHeight\": 8\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"trendLines\": [],\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"graphs\": [\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"balloonText\": \"<strong>[[title]]</strong> : [[value]]\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"bullet\": \"round\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"bulletBorderThickness\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"bulletSize\": 8,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"dashLength\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"id\": \"AmGraph-1\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"lineThickness\": 3,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"title\": \"대구광역시\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"valueField\": \"column-2\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t} /* ,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"balloonText\": \"<strong>[[title]]</strong> : [[value]]\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"bullet\": \"round\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"bulletBorderThickness\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"bulletSize\": 8,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"dashLength\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"id\": \"AmGraph-2\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"lineThickness\": 3,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"title\": \"대구시장\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"valueField\": \"column-3\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t}  */\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t],\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"guides\": [],\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"valueAxes\": [\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"id\": \"ValueAxis-1\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"axisThickness\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"color\": \"#c0c0c0\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"dashLength\": 2,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"gridAlpha\": 1,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"gridColor\": \"#D8D8D8\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"tickLength\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"title\": \"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t],\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"allLabels\": [],\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"balloon\": {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"color\": \"#FFFFFF\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"fadeOutDuration\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"fillAlpha\": 0.67,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"fillColor\": \"#000000\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"fontSize\": 11,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"horizontalPadding\": 10,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"pointerWidth\": 5,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"shadowAlpha\": 0.3\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"legend\": {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"enabled\": true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"align\": \"center\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"autoMargins\": false,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"color\": \"#444444\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"equalWidths\": false,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"marginLeft\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"marginRight\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"markerLabelGap\": 6,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"markerSize\": 11,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"markerType\": \"circle\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"spacing\": 15,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"useGraphSettings\": true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"valueText\": \"\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"verticalGap\": 2\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"titles\": [],\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"dataProvider\": []\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t};\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tchart1 = AmCharts.makeChart(\"chart_c4_01\", chartOption);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tchart1.addListener(\"clickGraphItem\", function(event){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar fulldate = event.item.dataContext.date;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar field = event.item.graph.valueField;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t//1@1 (분류체계-구분-대구시청)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar codeList = \"\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tif(field==\"column-2\"){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tcodeList = \"1@1\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar param = \"scope=\" + scope + \"&keyword=\" + keyword + \"&sDate=\" + fulldate + \"&eDate=\" + fulldate + \"&codeList=\" + codeList+\"&tier=\"+tier;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tpopupOpen( \"../popup/rel_info.jsp?\" + param);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\t})();\r\n");
      out.write("\t\t\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div style=\"width: 100%;text-align: right;margin-top: 15px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"fs11\"> * 설정된 키워드로 수집된 데이터 중 유효데이터의 일자별 추이 그래프 </span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- Loader -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"ui_loader v0\"><span class=\"loader\">Load</span></div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"ui_loader v1\"><span class=\"loader\"></span><p>saving...</p></div>\r\n");
      out.write("\t\t\t\t\t\t<!-- // Loader -->\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- // 온라인 동향 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- 주요 시정 채널 별 성향 & 서울시장 채널 별 성향 -->\r\n");
      out.write("\t\t\t\t<div class=\"ui_boxs_00\" class=\"section_hidden\">\r\n");
      out.write("\t\t\t\t\t<!-- 주요 시정 채널 별 성향 -->\r\n");
      out.write("\t\t\t\t\t<section id=\"s_c5_1\" class=\"ui_box_00 ui_shadow_00\" style=\"width: 100%\">\r\n");
      out.write("\t\t\t\t\t\t<h3><span class=\"ui_bullet_00\">●</span>채널 별 성향</h3>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"title_rc\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"ui_btn_02 ui_shadow_01\" title=\"Excel Download\" onclick=\"excelDownload('2', '채널 별 성향'); return false;\"><span class=\"icon excel\">Excel Download</span></button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"chart_c5_01\" class=\"ui_chart\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvar chart2;\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t(function(){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar chartOption = {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"type\": \"pie\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"balloonText\": \"<strong>[[category]]</strong><br>[[value]]건\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"innerRadius\": \"70%\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"labelRadius\": -15,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"labelText\": \"[[percents]]%\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"pullOutRadius\": \"0%\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"radius\": \"47%\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"startRadius\": \"0%\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"colors\": [\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"#5ba1e0\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"#ea7070\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"#888888\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t],\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"marginBottom\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"marginTop\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"pullOutDuration\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"startDuration\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"titleField\": \"category\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"valueField\": \"column-1\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"color\": \"#FFFFFF\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"percentPrecision\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"allLabels\": [\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"align\": \"center\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"bold\": true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"color\": \"#5ba1e0\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"id\": \"Label-1\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"size\": 17,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"text\": \"VOLUME\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"y\": 60\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"align\": \"center\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"bold\": true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"color\": \"#444444\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"id\": \"Label-2\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"size\": 30,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"text\": \"\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"y\": 90\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t],\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"balloon\": {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"color\": \"#FFFFFF\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"fadeOutDuration\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"fillAlpha\": 0.67,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"fillColor\": \"#000000\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"fontSize\": 11,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"horizontalPadding\": 20,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"pointerWidth\": 5,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"shadowAlpha\": 0.3,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"verticalPadding\": 6\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"titles\": [],\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"dataProvider\": []\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t};\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tchart2 = AmCharts.makeChart(\"chart_c5_01\", chartOption);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tchart2.addListener(\"clickSlice\", function(event){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tvar senti = event.dataItem.dataContext.category;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tvar codeList = \"\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tif(senti==\"긍정\"){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tcodeList += \"9@1\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t}else if(senti==\"부정\"){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tcodeList += \"9@2\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t}else if(senti==\"중립\"){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tcodeList += \"9@3\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tvar param = \"scope=\" + scope + \"&keyword=\" + keyword + \"&sDate=\" + sDate + \"&eDate=\" + eDate + \"&codeList=\" + codeList+\"&tier=\"+tier;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tpopupOpen( \"../popup/rel_info.jsp?\" + param);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t})();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"chart_c5_02\" class=\"ui_chart\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar chart3;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t(function(){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvar chartOption = {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"type\": \"serial\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"categoryField\": \"category\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"columnWidth\": 0.4,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"marginBottom\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"marginTop\": 10,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"colors\": [\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"#5ba1e0\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"#ea7070\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"#888888\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t],\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"addClassNames\": true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"pathToImages\": \"../asset/img/amchart/\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"percentPrecision\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"categoryAxis\": {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"labelRotation\": 45,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"minHorizontalGap\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t/* \"autoWrap\": true, */\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"gridPosition\": \"start\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"twoLineMode\": true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"axisColor\": \"#D8D8D8\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"color\": \"#444444\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"gridAlpha\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"tickLength\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"labelFunction\":function(data){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tif(data.length>4){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\treturn data.substring(0,4) + \"..\";\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\treturn data;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"chartCursor\": {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"enabled\": true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"cursorColor\": \"#000000\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"trendLines\": [],\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"graphs\": [\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"balloonText\": \"<strong>[[title]]</strong> : [[value]]\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"bulletBorderThickness\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"bulletSize\": 5,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"fillAlphas\": 1,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"id\": \"AmGraph-1\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"markerType\": \"circle\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"title\": \"긍정\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"type\": \"column\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"valueField\": \"column-2\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"balloonText\": \"<strong>[[title]]</strong> : [[value]]\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"bulletBorderThickness\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"bulletSize\": 5,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"fillAlphas\": 1,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"id\": \"AmGraph-2\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"markerType\": \"circle\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"title\": \"부정\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"type\": \"column\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"valueField\": \"column-3\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"balloonText\": \"<strong>[[title]]</strong> : [[value]]\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"bulletBorderThickness\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"bulletSize\": 5,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"fillAlphas\": 1,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"id\": \"AmGraph-3\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"markerType\": \"circle\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"title\": \"중립\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"type\": \"column\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"valueField\": \"column-4\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t],\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"guides\": [],\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"valueAxes\": [\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"id\": \"ValueAxis-1\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"stackType\": \"regular\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"axisThickness\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"color\": \"#c0c0c0\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"dashLength\": 2,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"gridAlpha\": 1,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"gridColor\": \"#D8D8D8\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"tickLength\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"title\": \"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t],\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"allLabels\": [],\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"balloon\": {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"color\": \"#FFFFFF\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"fadeOutDuration\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"fillAlpha\": 0.67,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"fillColor\": \"#000000\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"fontSize\": 11,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"horizontalPadding\": 10,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"pointerWidth\": 5,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"shadowAlpha\": 0.3\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"legend\": {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"enabled\": true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"align\": \"center\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"autoMargins\": false,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"color\": \"#444444\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"equalWidths\": false,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"marginLeft\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"marginRight\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"markerLabelGap\": 6,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"markerSize\": 11,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"markerType\": \"circle\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"spacing\": 15,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"useGraphSettings\": true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"valueText\": \"\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"verticalGap\": 2\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"titles\": [],\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"dataProvider\": []\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t};\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tchart3 = AmCharts.makeChart(\"chart_c5_02\", chartOption);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tchart3.addListener(\"clickGraphItem\", function(event){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar iccode = event.item.dataContext.iccode;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar field = event.item.graph.valueField;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar codeList = \"6@\"+iccode;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tif(field==\"column-2\"){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tcodeList += \"/9@1\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t}else if(field==\"column-3\"){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tcodeList += \"/9@2\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t}else if(field==\"column-4\"){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tcodeList += \"/9@3\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar param = \"scope=\" + scope + \"&keyword=\" + keyword + \"&sDate=\" + sDate + \"&eDate=\" + eDate + \"&codeList=\" + codeList+\"&tier=\"+tier;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tpopupOpen( \"../popup/rel_info.jsp?\" + param);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\t})();\r\n");
      out.write("\t\t\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div style=\"width: 100%;text-align: right;margin-top: 15px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"fs11\"> * 설정된 키워드로 수집된 데이터 중 유효데이터의 채널별 정보량 및 성향 </span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- Loader -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"ui_loader v0\"><span class=\"loader\">Load</span></div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"ui_loader v1\"><span class=\"loader\"></span><p>saving...</p></div>\r\n");
      out.write("\t\t\t\t\t\t<!-- // Loader -->\r\n");
      out.write("\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t\t<!-- // 주요 시정 채널 별 성향 -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- // 주요 시정 채널 별 성향 & 서울시장 채널 별 성향 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- 포탈 TOP 노출 현황 -->\r\n");
      out.write("\t\t\t\t<div class=\"ui_boxs_00\" class=\"section_hidden\">\r\n");
      out.write("\t\t\t\t\t<section id=\"s_c6_1\" class=\"ui_box_00 ui_shadow_00\">\r\n");
      out.write("\t\t\t\t\t\t<h3 class=\"no_bd\"><span class=\"ui_bullet_00\">●</span>포탈 TOP 노출 현황</h3>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"title_rc\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"ui_btn_02 ui_shadow_01\" title=\"Excel Download\" onclick=\"excelDownload('4', '포탈 TOP 노출 현황'); return false;\"><span class=\"icon excel\">Excel Download</span></button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <ul class=\"ui_tab_00\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><input id=\"s_c6_1_radio_00\" type=\"radio\" name=\"s_c6_1_radio\" value=\"0\" checked><label for=\"s_c6_1_radio_00\"><span>전체</span></label></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><input id=\"s_c6_1_radio_01\" type=\"radio\" name=\"s_c6_1_radio\" value=\"1\" ><label for=\"s_c6_1_radio_01\"><span>대구광역시</span></label></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><input id=\"s_c6_1_radio_02\" type=\"radio\" name=\"s_c6_1_radio\" value=\"2\" ><label for=\"s_c6_1_radio_02\"><span>대구시장</span></label></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul> -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"ui_board_list_00\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<table id=\"section04_contents\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<caption>관련정보 목록</caption>\r\n");
      out.write("\t\t\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t<col style=\"width:130px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<col style=\"width:130px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<col>\r\n");
      out.write("\t\t\t\t\t\t\t\t<col style=\"width:110px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"col\"><span>포탈구분</span></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"col\"><span>영역</span></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"col\"><span>제목</span></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"col\"><span>최초노출일시</span></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr><td colspan=\"4\"></td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr><td colspan=\"4\"></td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr><td colspan=\"4\">데이터가 없습니다</td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr><td colspan=\"4\"></td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr><td colspan=\"4\"></td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><strong>네이버</strong></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><strong>뉴스</strong></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"title\"><a href=\"http://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=101&oid=015&aid=0003828416\" target=\"_blank\">광주광역시 주민참여형 '우리동네 살리기' 현장 가보니</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>2017-09-25 17:41</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><strong>네이버</strong></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><strong>뉴스</strong></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"title\"><a href=\"http://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=079&aid=0003016303\" target=\"_blank\">'광주 알바 청소년' 10 명 중 3명 최저임금 못 받아</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>2017-09-25 17:35</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><strong>네이버</strong></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><strong>뉴스</strong></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"title\"><a href=\"http://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=079&aid=0003016293\" target=\"_blank\">윤장현 광주시장, 5·18 세계에 알린 기여 공로패 받아</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>2017-09-25 17:31</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><strong>네이버</strong></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><strong>뉴스</strong></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"title\"><a href=\"http://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=001&aid=0009569932\" target=\"_blank\">\"써준 원고 읽는 시정질문…\" 광주시 사무관 SNS글 파문</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>2017-09-25 11:32</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><strong>네이버</strong></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><strong>뉴스</strong></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"title\"><a href=\"http://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=100&oid=018&aid=0003931495\" target=\"_blank\">수도요금 서울 ㎥당 569원 불과…울산 865원·부산 728원</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>2017-09-25 11:16</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <tr><td colspan=\"4\"></td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr><td colspan=\"4\"></td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr><td colspan=\"4\"></td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr><td colspan=\"4\"></td></tr> --> \r\n");
      out.write("\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"top_paging\" class=\"paginate\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"page_prev disabled\">이전페이지</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"active\" onclick=\"popupOpen( '../popup/rel_info.jsp' );return false;\">1</a>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <a href=\"#\" onclick=\"popupOpen( '../popup/rel_info.jsp' );return false;\">2</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">3</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">4</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">5</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">6</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">7</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">8</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">9</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">10</a> -->\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"page_next\">다음페이지</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div style=\"width: 100%;text-align: right;margin-top: 15px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"fs11\"> * 제목에 ‘대구‘ 키워드가 있는 기사 중 포탈메인화면에 노출된 기사리스트 </span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- Loader -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"ui_loader v0\"><span class=\"loader\">Load</span></div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"ui_loader v1\"><span class=\"loader\"></span><p>saving...</p></div>\r\n");
      out.write("\t\t\t\t\t\t<!-- // Loader -->\r\n");
      out.write("\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- // 포탈 TOP 노출 현황 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- 포탈 댓글 현황/분석 -->\r\n");
      out.write("\t\t\t\t<div class=\"ui_boxs_00\">\r\n");
      out.write("\t\t\t\t\t<div class=\"ui_box_00 ui_shadow_00 f_clear\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 포탈 댓글 현황 -->\r\n");
      out.write("\t\t\t\t\t\t\t<section id=\"s_c7_1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3 class=\"no_bd\"><span class=\"ui_bullet_00\">●</span>포탈 댓글 현황</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"title_rc v2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<strong>날짜</strong>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" id=\"c_15_dp_00\" class=\"ui_datepicker_input\" value=\"");
      out.print(eDate);
      out.write("\"><label for=\"c_15_dp_00\" class=\"invisible\">날짜선택</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"button\" class=\"ui_btn_02 ui_shadow_01\" title=\"검색\" onclick=\"summary.portalSearch(1);\"><span class=\"icon search\">검색</span></button>\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"button\" class=\"ui_btn_02 ui_shadow_01\" title=\"Excel Download\" onclick='excelDownload(\"5_1\", \"포탈 댓글 현황\"); return false;'><span class=\"icon excel\">Excel Download</span></button>\r\n");
      out.write("<!-- \t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"ui_btn_02 ui_shadow_01\" title=\"Excel Download\" onclick=\"getExcel( event, &quot;../temp/temp_excel.jsp&quot;, &quot;{\\&quot;test\\&quot;:\\&quot;test\\&quot;}&quot; );\"><span class=\"icon excel\">Excel Download</span></button> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- <ul class=\"ui_tab_00\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><input id=\"s_c6_1_radio_03\" type=\"radio\" name=\"s_c6_2_radio\" value=\"0\"  checked><label for=\"s_c6_1_radio_03\"><span>전체</span></label></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><input id=\"s_c6_1_radio_04\" type=\"radio\" name=\"s_c6_2_radio\" value=\"1\" ><label for=\"s_c6_1_radio_04\"><span>대구광역시</span></label></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><input id=\"s_c6_1_radio_05\" type=\"radio\" name=\"s_c6_2_radio\" value=\"2\" ><label for=\"s_c6_1_radio_05\"><span>대구시장</span></label></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"ui_board_list_00\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<caption>관련정보 목록</caption>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col style=\"width:150px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col style=\"width:170px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col style=\"width:110px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th scope=\"col\"><span>포탈구분</span></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th scope=\"col\"><span>댓글</span></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th scope=\"col\"><span>제목</span></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th scope=\"col\"><span>일자</span></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tbody id=\"portal_tbody\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- 데이터 없는 경우\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr><td colspan=\"4\"></td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr><td colspan=\"4\"></td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr><td colspan=\"4\"></td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr><td colspan=\"4\">데이터가 없습니다</td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr><td colspan=\"4\"></td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr><td colspan=\"4\"></td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr><td colspan=\"4\"></td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t-->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- <tr class=\"active\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td><span>nKBS 뉴스</span></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td><a href=\"#\">636</a> (<a href=\"#\" class=\"ui_fc_blue\" title=\"긍정 : 999,999,999\">999K</a>/<a href=\"#\" class=\"ui_fc_red\" title=\"부정 : 999,999,999\">999K</a>/<a href=\"#\" class=\"ui_fc_green\" title=\"중립 : 999,999,999\">999K</a>)</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"title\"><a href=\"#\" target=\"_blank\">황사,미세먼지 이길 '디톡스식품' 인기리 판매</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>12/20</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr><td colspan=\"4\"></td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr><td colspan=\"4\"></td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr><td colspan=\"4\"></td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr><td colspan=\"4\"></td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr><td colspan=\"4\"></td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr><td colspan=\"4\"></td></tr> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"section04_paging\" class=\"paginate\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- \t<a href=\"#\" class=\"page_prev disabled\">이전페이지</a>\t\t버튼 활성화시 disabled 클래스 제거\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"active\" onclick=\"popupOpen( '../popup/rel_info.jsp' );return false;\">1</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\" onclick=\"popupOpen( '../popup/rel_info.jsp' );return false;\">2</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\">3</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\">4</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\">5</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\">6</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\">7</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\">8</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\">9</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\">10</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"page_next\">다음페이지</a> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"height:3px;\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- <div class=\"bot_con_info\" style=\"text-align: right;\">* 포탈 댓글은 최초 수집 후 72시간까지 제공하며, 수동 수집은 요청 후 최대 30분까지 소요됩니다.</div> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"width: 100%;text-align: right;margin-top: 15px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"fs11\"> * ‘대구시’, ‘대구광역시’로 수집되는 모든 기사리스트, 댓글 많은 순으로 정렬 </span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Loader -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"ui_loader v0\" id=\"portal_reply_loader\" ><span class=\"loader\">Load</span></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"ui_loader v1\"><span class=\"loader\"></span><p>saving...</p></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- // Loader -->\r\n");
      out.write("\t\t\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 포탈 댓글 현황 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 기사 댓글 분석 -->\r\n");
      out.write("\t\t\t\t\t\t\t<section id=\"s_c7_2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3 class=\"no_bd\"><span class=\"ui_bullet_00\">●</span>기사 댓글 분석<strong id=\"article_reply_ana\"></strong></h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- 성향별 점유율 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<section id=\"s_c7_2_1\" class=\"ui_box_00\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h4>성향별 점유율</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"title_rc\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"ui_btn_02 ui_shadow_01\" title=\"Excel Download\" onclick=\"excelDownload('5_2', '성향별 점유율'); return false;\"><span class=\"icon excel\">Excel Download</span></button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div id=\"chart_c7_01\" class=\"ui_chart\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tvar chart6;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t(function(){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tvar chartOption ={\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"type\": \"pie\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"addClassNames\": true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"balloonText\": \"<strong>[[category]]</strong><br>[[value]]건\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"innerRadius\": \"70%\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"labelRadius\": -17,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"labelText\": \"[[percents]]%\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"pullOutRadius\": \"0%\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"radius\": \"47%\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"startRadius\": \"0%\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"colors\": [\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"#5ba1e0\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"#ea7070\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"#888888\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t],\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"marginBottom\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"marginTop\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"pullOutDuration\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"startDuration\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"titleField\": \"category\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"valueField\": \"column1\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"color\": \"#FFFFFF\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"percentPrecision\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"allLabels\": [\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"align\": \"center\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"bold\": true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"color\": \"#5ba1e0\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"id\": \"Label-1\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"size\": 22,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"text\": \"VOLUME\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"y\": 90\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"align\": \"center\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"bold\": true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"color\": \"#444444\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"id\": \"Label-2\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"size\": 32,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"text\": \"\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"y\": 130\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t],\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"balloon\": {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"color\": \"#FFFFFF\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"fadeOutDuration\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"fillAlpha\": 0.67,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"fillColor\": \"#000000\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"fontSize\": 11,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"horizontalPadding\": 20,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"pointerWidth\": 5,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"shadowAlpha\": 0.3,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"verticalPadding\": 6\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"legend\": {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"enabled\": true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"align\": \"center\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"autoMargins\": false,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"color\": \"#444444\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"equalWidths\": false,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"marginLeft\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"marginRight\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"markerLabelGap\": 6,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"markerSize\": 11,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"markerType\": \"circle\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"spacing\": 10,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"valueText\": \"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"titles\": [],\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"dataProvider\": []\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t};\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t/* {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"type\": \"pie\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"addClassNames\": true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"balloonText\": \"<strong>[[category]]</strong><br>[[value]]건\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"innerRadius\": \"50%\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"labelRadius\": -17,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"labelText\": \"[[percents]]%\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"pullOutRadius\": \"0%\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"radius\": \"40%\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"startRadius\": \"0%\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"colors\": [\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"#5ba1e0\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"#ea7070\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"#888888\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t],\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"marginBottom\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"marginTop\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"pullOutDuration\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"startDuration\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"titleField\": \"category\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"valueField\": \"column1\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"color\": \"#FFFFFF\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"percentPrecision\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"allLabels\": [],\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"balloon\": {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"color\": \"#444444\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"fadeOutDuration\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"fillAlpha\": 0.9,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"fillColor\": \"#ffffff\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"fontSize\": 11,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"horizontalPadding\": 20,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"pointerWidth\": 5,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"shadowAlpha\": 0.3,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"verticalPadding\": 6\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"categoryAxis\": {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"gridPosition\": \"start\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"twoLineMode\": true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"axisColor\": \"#D8D8D8\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"color\": \"#444444\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"gridAlpha\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"tickLength\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"labelFunction\":function(data){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tif(data.length>4){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\treturn data.substring(0,4) + \"..\";\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\treturn data;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"legend\": {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"enabled\": true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"align\": \"center\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"autoMargins\": false,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"color\": \"#444444\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"equalWidths\": false,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"marginLeft\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"marginRight\": 0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"markerLabelGap\": 6,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"markerSize\": 11,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"markerType\": \"circle\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"spacing\": 10,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"valueText\": \"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"titles\": [],\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"dataProvider\": [\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"category\": \"긍정\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column1\": 0\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"category\": \"부정\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column1\": 0\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"category\": \"중립\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"column1\": 0\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t]\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t}; */\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tchart6 = AmCharts.makeChart(\"chart_c7_01\", chartOption);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tchart6.addListener(\"clickSlice\", function(event){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tvar senti = event.dataItem.dataContext.category;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tvar r_trnd = \"\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tif(senti==\"긍정\"){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tr_trnd = \"1\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}else if(senti==\"부정\"){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tr_trnd = \"2\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}else if(senti==\"중립\"){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tr_trnd = \"3\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tvar p_date = $(\"#c_15_dp_00\").val();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tsummary.getReplyPopUp(DOC_ID, p_date, 0, 1, r_trnd, '');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t})();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- Loader -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"ui_loader v0\"><span class=\"loader\">Load</span></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"ui_loader v1\"><span class=\"loader\"></span><p>saving...</p></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- // Loader -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- // 성향별 점유율 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- 연관어 클라우드 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- <section id=\"s_c7_2_2\" class=\"ui_box_00\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h4>연관어 클라우드</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"title_rc\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"ui_btn_02 ui_shadow_01\" title=\"Excel Download\" onclick=\"excelDownload('5_3', '연관어 클라우드'); return false;\"><span class=\"icon excel\">Excel Download</span></button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"spider_wrap\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div id=\"spider_00\" class=\"ui_spider_box v2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"line_area\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"all\"><a href=\"#\"><strong>대구광역시</strong><span> </span></a></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"item postive\"><a href=\"#\"><strong> </strong><span> </span></a></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"item postive\"><a href=\"#\"><strong> </strong><span> </span></a></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"item postive\"><a href=\"#\"><strong> </strong><span> </span></a></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"item postive\"><a href=\"#\"><strong> </strong><span> </span></a></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"item postive\"><a href=\"#\"><strong> </strong><span> </span></a></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"item postive\"><a href=\"#\"><strong> </strong><span> </span></a></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"item negative\"><a href=\"#\"><strong> </strong><span> </span></a></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"item negative\"><a href=\"#\"><strong> </strong><span> </span></a></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"item negative\"><a href=\"#\"><strong> </strong><span> </span></a></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"item negative\"><a href=\"#\"><strong> </strong><span> </span></a></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"item negative\"><a href=\"#\"><strong> </strong><span> </span></a></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"item neutral\"><a href=\"#\"><strong> </strong><span> </span></a></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"item neutral\"><a href=\"#\"><strong> </strong><span> </span></a></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"item neutral\"><a href=\"#\"><strong> </strong><span> </span></a></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"item neutral\"><a href=\"#\"><strong> </strong><span> </span></a></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<script type=\"text/javascript\" src=\"../asset/js/jquery.ui_spider.js\"></script>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<script type=\"text/javascript\" src=\"../asset/js/jquery.domline.js\"></script>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<script type=\"text/javascript\" src=\"../asset/js/jquery.transform2d.min.js\"></script>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t(function($) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t$( \"#spider_00\" ).ui_spider();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t$( \"#spider_00 a\" ).click( function($e){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tpopupOpen( \"../popup/rel_info.jsp\" );\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t})(jQuery);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tLoader\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"ui_loader v0\"><span class=\"loader\">Load</span></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"ui_loader v1\"><span class=\"loader\"></span><p>saving...</p></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t// Loader\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</section> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- // 연관어 클라우드 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- 연관키워드 -->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <section id=\"s_c3_1\" class=\"ui_box_00\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4></h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"title_rc\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"ui_btn_02 ui_shadow_01\" title=\"Excel Download\" onclick=\"excelDownload('4_1', '연관키워드'); return false;\"><span class=\"icon excel\">Excel Download</span></button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"tag_cloud_01\" class=\"ui_word_cloud no_data\"></div>\t\t\t\t데이터 없는 경우 no_data 클래스 추가\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\tLoader\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"ui_loader v0\"><span class=\"loader\">Load</span></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"ui_loader v1\"><span class=\"loader\"></span><p>saving...</p></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t// Loader\r\n");
      out.write("\t\t\t\t\t\t\t</section> -->\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 연관어 클라우드 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<section id=\"s_c7_2_2\" class=\"ui_box_00\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h4>연관어 클라우드</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"title_rc\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"ui_btn_02 ui_shadow_01\" title=\"Excel Download\" onclick=\"excelDownload('5_3', '연관어 클라우드'); return false;\"><span class=\"icon excel\">Excel Download</span></button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"wrap\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"ui_jqw_cloud\" style=\"height:299px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div id=\"tag_cloud_02_04_01\" class=\"wrap\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<!-- <script>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t(function(){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t$(\"#tag_cloud_02_04_01\").each( function(){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tvar opt = {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\twords: [\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{weight: 33721, color: \"#5ba1e0\", word: \"좋아요\"},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{weight: 30674, color: \"#5ba1e0\", word: \"스타\"},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{weight: 20729, color: \"#5ba1e0\", word: \"팔로우\"},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{weight: 13375, color: \"#5ba1e0\", word: \"인스타그램\"},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{weight: 11904, color: \"#5ba1e0\", word: \"인스타\"},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{weight: 10050, color: \"#5ba1e0\", word: \"구매\"},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{weight: 9840,  color: \"#5ba1e0\", word: \"사용\"},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{weight: 8801,  color: \"#5ba1e0\", word: \"갤럭시\"},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{weight: 8676,  color: \"#5ba1e0\", word: \"카톡\"},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{weight: 7756,  color: \"#5ba1e0\", word: \"카메라\"},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{weight: 7733,  color: \"#5ba1e0\", word: \"아이폰7\"},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{weight: 7582,  color: \"#ea7070\", word: \"너무\"},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{weight: 7571,  color: \"#ea7070\", word: \"폰케이스\"},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{weight: 7462,  color: \"#ea7070\", word: \"주말\"},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{weight: 7414,  color: \"#ea7070\", word: \"애플\"},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{weight: 6618,  color: \"#ea7070\", word: \"맛집\"},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{weight: 6409,  color: \"#ea7070\", word: \"핸드폰\"},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{weight: 6287,  color: \"#ea7070\", word: \"광안리\"},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{weight: 6270,  color: \"#ea7070\", word: \"여행\"},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{weight: 5982,  color: \"#ea7070\", word: \"일상愛\"},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{weight: 5738,  color: \"#888888\", word: \"커피\"},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{weight: 5655,  color: \"#888888\", word: \"아이폰6\"},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{weight: 5510,  color: \"#888888\", word: \"스마트폰\"},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{weight: 5315,  color: \"#888888\", word: \"한남동\"},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{weight: 5188,  color: \"#888888\", word: \"패션\"},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{weight: 5100,  color: \"#888888\", word: \"iphone\"},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{weight: 4845,  color: \"#888888\", word: \"할인\"},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{weight: 4783,  color: \"#888888\", word: \"디자인\"},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{weight: 4773,  color: \"#888888\", word: \"구글\"},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{weight: 4691,  color: \"#888888\", word: \"모바일\"},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t],\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclickFunc: function(){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tpopupOpen( \"../popup/rel_info.jsp\" );\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tconsole.log( \"클릭 메서드 연결\" );\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t// 선택아이템 제거\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t//$( \"#tag_cloud_02_04_02\" ).data( \"jqw_cloud\" ).activeDisable();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t//$( \"#tag_cloud_02_04_03\" ).data( \"jqw_cloud\" ).activeDisable();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t$( this ).jqw_cloud( opt );\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t})();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</script> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- Loader -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"ui_loader v0\"><span class=\"loader\">Load</span></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"ui_loader v1\"><span class=\"loader\"></span><p>saving...</p></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- // Loader -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- // 연관어 클라우드 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Loader -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"ui_loader v1\"><span class=\"loader\"></span><p>saving...</p></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- // Loader -->\r\n");
      out.write("\t\t\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- // 연관키워드 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 포탈 댓글 분석 -->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- 포탈 댓글 현황/분석 -->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- 소셜 이슈 리스트 -->\r\n");
      out.write("\t\t\t\t<div class=\"ui_boxs_00\">\r\n");
      out.write("\t\t\t\t\t<section id=\"s_c8_1\" class=\"ui_box_00 ui_shadow_00\">\r\n");
      out.write("\t\t\t\t\t\t<h3 class=\"no_bd\"><span class=\"ui_bullet_00\">●</span>소셜미디어 이슈 리스트</h3>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"title_rc\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"ui_btn_02 ui_shadow_01\" title=\"Excel Download\" onclick=\"excelDownload('6', '소셜미디어 이슈 리스트'); return false;\"><span class=\"icon excel\">Excel Download</span></button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"ui_board_list_00\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<table id=\"section06_contents\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<caption>관련정보 목록</caption>\r\n");
      out.write("\t\t\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t<col style=\"width:200px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<col>\r\n");
      out.write("\t\t\t\t\t\t\t\t<col style=\"width:120px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<col style=\"width:120px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"col\"><span>출처</span></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"col\"><span>제목</span></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"col\"><span>확산 건수</span></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"col\"><span>수집일</span></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr><td colspan=\"4\">&nbsp;</td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr><td colspan=\"4\">&nbsp;</td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr><td colspan=\"4\">&nbsp;</td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr><td colspan=\"4\">&nbsp;</td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr><td colspan=\"4\">데이터가 없습니다</td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr><td colspan=\"4\">&nbsp;</td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr><td colspan=\"4\">&nbsp;</td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr><td colspan=\"4\">&nbsp;</td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr><td colspan=\"4\">&nbsp;</td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr><td colspan=\"4\">&nbsp;</td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><span title=\"네이버\">네이버</span></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>2017-01-01</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"title\"><a href=\"#\" target=\"_blank\">황사,미세먼지 이길 '디톡스식품' 인기리 판매</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><span title=\"이재현,최순실 이재현\">이재현,최순실 이재현</span></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr><td colspan=\"4\"></td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr><td colspan=\"4\"></td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr><td colspan=\"4\"></td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr><td colspan=\"4\"></td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr><td colspan=\"4\"></td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr><td colspan=\"4\"></td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr><td colspan=\"4\"></td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr><td colspan=\"4\"></td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr><td colspan=\"4\"></td></tr> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"section06_paging\" class=\"paginate\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <a href=\"#\" class=\"page_prev disabled\">이전페이지</a>\t\t버튼 활성화시 disabled 클래스 제거\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"active\" onclick=\"popupOpen( '../popup/rel_info.jsp' );return false;\">1</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" onclick=\"popupOpen( '../popup/rel_info.jsp' );return false;\">2</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">3</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">4</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">5</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">6</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">7</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">8</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">9</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">10</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"page_next\">다음페이지</a> -->\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div style=\"width: 100%;text-align: right;margin-top: 15px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"fs11\"> * ‘대구시’, ‘대구광역시’로 수집되는 개인미디어(블로그,카페,커뮤니티,트위터,페이스북) 게시물리스트, 확산 수량 많은 순으로 정렬 </span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- Loader -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"ui_loader v0\"><span class=\"loader\">Load</span></div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"ui_loader v1\"><span class=\"loader\"></span><p>saving...</p></div>\r\n");
      out.write("\t\t\t\t\t\t<!-- // Loader -->\r\n");
      out.write("\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- // 소셜 이슈 리스트 -->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Include Footer -->\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../inc/inc_footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t<!-- // Include Footer -->\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else log(t.getMessage(), t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
